// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnhQUUikn4uJgg0sD6EOfMm0h-tyCn3ok',
    appId: '1:809887271886:web:bbc39b8fbaa4e6df88f99f',
    messagingSenderId: '809887271886',
    projectId: 'chat-app-3d5b4',
    authDomain: 'chat-app-3d5b4.firebaseapp.com',
    storageBucket: 'chat-app-3d5b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5jhBk2omkY9mWd2UxDacGI3hXS1LaT9s',
    appId: '1:809887271886:android:2faa3b97a301c56488f99f',
    messagingSenderId: '809887271886',
    projectId: 'chat-app-3d5b4',
    storageBucket: 'chat-app-3d5b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdhgpZmbwDvBZ-cfwywPkvWG0v1EOGapo',
    appId: '1:809887271886:ios:186b1df39e89e28e88f99f',
    messagingSenderId: '809887271886',
    projectId: 'chat-app-3d5b4',
    storageBucket: 'chat-app-3d5b4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdhgpZmbwDvBZ-cfwywPkvWG0v1EOGapo',
    appId: '1:809887271886:ios:186b1df39e89e28e88f99f',
    messagingSenderId: '809887271886',
    projectId: 'chat-app-3d5b4',
    storageBucket: 'chat-app-3d5b4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnhQUUikn4uJgg0sD6EOfMm0h-tyCn3ok',
    appId: '1:809887271886:web:61ea8939fa57804e88f99f',
    messagingSenderId: '809887271886',
    projectId: 'chat-app-3d5b4',
    authDomain: 'chat-app-3d5b4.firebaseapp.com',
    storageBucket: 'chat-app-3d5b4.firebasestorage.app',
  );
}
